### ISSUE TITLE
Note on Python Bytes awesome packages

### ISSUE THREAD

**Issue by antonalekseev** [JackMcKew/jackmckew.dev#5]
> There was one episode that referenced some amazing examples of GUIs built in Tkinter, unfortunately I have been unable to find it again. My note that I had down was `63 GUIs in Tkinter`.

Wasn't it the Item #6 from https://pythonbytes.fm/episodes/show/63/we-re-still-on-a-desktop-gui-kick?

**Comment by JackMcKew** [comment]
Hi Anton,

Thank you so much for the suggestion!

Upon revisiting episode 63, I noticed that it was under item #4, just didn't have a obvious title, so I would've brushed over it.

[The post should be updated now ](https://jackmckew.dev/python-bytes-awesome-package-list.html#great-examples-of-tkinter)and I've thrown in a shout out for yourself :)

P.S I also fixed the heading anchor hyperlinks because I noticed that wasn't working
